### PR TITLE
add dagmc model of baby experiment

### PR DESCRIPTION
**Pull request by jbae11**
Hey yall, thought I'd do something useful for once and submit this PR - this is a dagmc model of the same openmc files here - it returns the same TBR as the CSG model, and has a tet-mesh h5m file for tetmesh tallying of TBR in the salt. Feel free to reject or edit as you see fit :)

### CODE REVIEW

**Comment by RemDelaporteMathurin** [comment]
Sorry @jbae11 I'm only seeing this now! Guess we haven't turned on notifications for this! I'll have a look asap!

**Comment by RemDelaporteMathurin** [comment]
@SteSeg @eepeterson @cdunn314 could you guys have a look at this?

**Comment by SteSeg** [comment]
Hi @jbae11! thank you for the . Do you also happen to have a python input to run the simulation?

**Comment by jbae11** [comment]
@SteSeg not really, most of them are generated automatically via FERMI, but I can provide code snippets for specific parts you're interested in?

**Comment by RemDelaporteMathurin** [comment]
@jbae11 this whole repository is automated, so without the code to run the model I don't think it should be in there. Maybe in the future [`libra-toolbox` suite](https://libra-toolbox.readthedocs.io/en/latest/)?

**Comment by jbae11** [comment]
makes sense!

**Pull request closed without merging**
